Repository OceanParcels/Parcels, pull requests merged in 2020-04, with the labels that each got.

#782 Fixing a bug with recent Structure-of-arrays PR and multiple grids
  parcels/codegenerator.py
  parcels/field.py
  parcels/include/parcels.h
  parcels/kernel.py
  parcels/particle.py
  parcels/particleset.py
  tests/test_fieldset_sampling.py
Labels: bug

#776 Stabilize dask loading of Ocean Model data
  .github/workflows/ci-workflow.yml
  parcels/examples/example_dask_chunk_OCMs.py
  parcels/examples/example_nemo_curvilinear.py
  parcels/field.py
  parcels/fieldset.py
  parcels/grid.py
  parcels/gridset.py
  parcels/kernel.py
  parcels/particle.py
  parcels/scripts/get_examples.py
  tests/test_fieldset.py
Labels: bug, help wanted

#829 Chunk MITgcm and WaveWatch3 fields
  parcels/field.py
Labels: enhancement, feature
